name: Build JAR 
on: workflow_dispatch 
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v4 
        with: 
          repository: ${{ github.repository  }} 
          ref: ${{ github.ref  }} 
      - name: Extract target project name 
        id: get-project 
        run: | 
          PROJECT_URL=$(cat project-to-build) 
          PROJECT_NAME=$(echo $PROJECT_URL | sed -E 's#https://github.com/(.+)/(.+)#\1/\2#')  
          echo "PROJECT=$PROJECT_NAME" >> $GITHUB_ENV 
      - name: Checkout target project code 
        uses: actions/checkout@v4 
        with: 
          repository: ${{ env.PROJECT }} 
          ref: main 
      - name: Set up JDK 17 
        uses: actions/setup-java@v4 
        with: 
          java-version: '17' 
          distribution: 'adopt' 
      - name: Build with Gradle 
        env: 
          GRADLE_OPTS: "-Dorg.gradle.daemon=true"  
        run: | 
          chmod +x gradlew 
          ./gradlew build --scan --stacktrace -Dorg.gradle.terms.agree=true  
      - name: Copy JAR File 
        run: |
          mkdir -p ./jar 
          cp build/libs/*.jar ./jar/custom_spider.jar  || true 
 
      - name: Upload artifact 
        uses: actions/upload-artifact@v4
        with:
          name: my-jar-file 
          path: ./jar/*.jar 
          retention-days: 3 
